// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9QFf0yFMGkNyWHQdVU-oLMrK-c8ZvBu8',
    appId: '1:979858760652:web:9573cfe9b9b08e74e73369',
    messagingSenderId: '979858760652',
    projectId: 'conexo-37711',
    authDomain: 'conexo-37711.firebaseapp.com',
    storageBucket: 'conexo-37711.firebasestorage.app',
    measurementId: 'G-EMM801R861',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDyMtM7Zy7yl0DtDApHTl3uQn5FMmgVY',
    appId: '1:979858760652:android:e29603f82f86c1bbe73369',
    messagingSenderId: '979858760652',
    projectId: 'conexo-37711',
    storageBucket: 'conexo-37711.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOjSRIZvNaaqPi9ZXQJGkEHr9cu_iw9VY',
    appId: '1:979858760652:ios:a9e30ed683a14777e73369',
    messagingSenderId: '979858760652',
    projectId: 'conexo-37711',
    storageBucket: 'conexo-37711.firebasestorage.app',
    androidClientId: '979858760652-9qicv1ok3tpovr13nat7o4mjrhb6igeb.apps.googleusercontent.com',
    iosClientId: '979858760652-e1710qquu1nihn6dbqldmm2s0b9omse6.apps.googleusercontent.com',
    iosBundleId: 'com.example.conexo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOjSRIZvNaaqPi9ZXQJGkEHr9cu_iw9VY',
    appId: '1:979858760652:ios:a9e30ed683a14777e73369',
    messagingSenderId: '979858760652',
    projectId: 'conexo-37711',
    storageBucket: 'conexo-37711.firebasestorage.app',
    androidClientId: '979858760652-9qicv1ok3tpovr13nat7o4mjrhb6igeb.apps.googleusercontent.com',
    iosClientId: '979858760652-e1710qquu1nihn6dbqldmm2s0b9omse6.apps.googleusercontent.com',
    iosBundleId: 'com.example.conexo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9QFf0yFMGkNyWHQdVU-oLMrK-c8ZvBu8',
    appId: '1:979858760652:web:26502048c87f56a0e73369',
    messagingSenderId: '979858760652',
    projectId: 'conexo-37711',
    authDomain: 'conexo-37711.firebaseapp.com',
    storageBucket: 'conexo-37711.firebasestorage.app',
    measurementId: 'G-BYLKG0EG36',
  );
}
